[
  {
    id: "loc1",
    streetAddress: "123 Elm St",
    city: "Springfield",
    state: "QLD",
    postalCode: 4000,
    appliances: [
      { name: "Air Conditioner", quantity: 2, hoursPerDay: 8, watts: 350 },
      { name: "Refrigerator", quantity: 1, hoursPerDay: 24, watts: 100 },
      { name: "Television", quantity: 1, hoursPerDay: 4, watts: 150 },
    ],
  },
  {
    id: "loc2",
    streetAddress: "456 Oak Ave",
    city: "Brisbane",
    state: "QLD",
    postalCode: 4005,
    appliances: [
      { name: "Heater", quantity: 1, hoursPerDay: 6, watts: 1500 },
      { name: "Washing Machine", quantity: 1, hoursPerDay: 1, watts: 500 },
      { name: "Toaster", quantity: 2, hoursPerDay: 0.5, watts: 800 },
    ],
  },
  {
    id: "loc3",
    streetAddress: "789 Maple Dr",
    city: "Gold Coast",
    state: "QLD",
    postalCode: 4217,
    appliances: [
      { name: "Dishwasher", quantity: 1, hoursPerDay: 2, watts: 1800 },
      { name: "Microwave", quantity: 1, hoursPerDay: 0.5, watts: 1000 },
      { name: "Lamp", quantity: 3, hoursPerDay: 5, watts: 60 },
    ],
  },
  {
    id: "loc4",
    streetAddress: "321 Pine Rd",
    city: "Cairns",
    state: "QLD",
    postalCode: 4870,
    appliances: [
      { name: "Oven", quantity: 1, hoursPerDay: 2, watts: 2150 },
      { name: "Coffee Maker", quantity: 1, hoursPerDay: 0.5, watts: 900 },
      { name: "Computer", quantity: 1, hoursPerDay: 8, watts: 200 },
    ],
  },
  {
    id: "loc5",
    streetAddress: "654 Cedar St",
    city: "Toowoomba",
    state: "QLD",
    postalCode: 4350,
    appliances: [
      { name: "Dryer", quantity: 1, hoursPerDay: 1.5, watts: 3000 },
      { name: "Refrigerator", quantity: 1, hoursPerDay: 24, watts: 100 },
      { name: "Lamp", quantity: 4, hoursPerDay: 6, watts: 60 },
    ],
  },
  {
    id: "loc6",
    streetAddress: "987 Birch Ave",
    city: "Rockhampton",
    state: "QLD",
    postalCode: 4700,
    appliances: [
      { name: "Microwave", quantity: 1, hoursPerDay: 0.3, watts: 1000 },
      { name: "Television", quantity: 2, hoursPerDay: 3, watts: 150 },
      { name: "Computer", quantity: 1, hoursPerDay: 5, watts: 200 },
    ],
  },
  {
    id: "loc7",
    streetAddress: "111 Palm St",
    city: "Townsville",
    state: "QLD",
    postalCode: 4810,
    appliances: [
      { name: "Washing Machine", quantity: 1, hoursPerDay: 0.8, watts: 500 },
      { name: "Dishwasher", quantity: 1, hoursPerDay: 1, watts: 1800 },
      { name: "Lamp", quantity: 1, hoursPerDay: 8, watts: 60 },
    ],
  },
  {
    id: "loc8",
    streetAddress: "555 Fern St",
    city: "Sunshine Coast",
    state: "QLD",
    postalCode: 4551,
    appliances: [
      { name: "Air Conditioner", quantity: 1, hoursPerDay: 10, watts: 350 },
      { name: "Coffee Maker", quantity: 1, hoursPerDay: 0.7, watts: 900 },
      { name: "Toaster", quantity: 1, hoursPerDay: 0.2, watts: 800 },
    ],
  },
  {
    id: "loc9",
    streetAddress: "222 Coral Way",
    city: "Mackay",
    state: "QLD",
    postalCode: 4740,
    appliances: [
      { name: "Heater", quantity: 1, hoursPerDay: 5, watts: 1500 },
      { name: "Refrigerator", quantity: 1, hoursPerDay: 24, watts: 100 },
      { name: "Television", quantity: 1, hoursPerDay: 2, watts: 150 },
    ],
  },
  {
    id: "loc10",
    streetAddress: "333 Willow Ln",
    city: "Ipswich",
    state: "QLD",
    postalCode: 4305,
    appliances: [
      { name: "Coffee Maker", quantity: 1, hoursPerDay: 0.5, watts: 900 },
      { name: "Oven", quantity: 1, hoursPerDay: 1.5, watts: 2150 },
      { name: "Computer", quantity: 1, hoursPerDay: 7, watts: 200 },
    ],
  },
];
